<a href="https://colab.research.google.com/github/Georgia-MAX-holic/theory/blob/main/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D/%EC%9D%B8%EC%BD%94%EB%94%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

데이터 전처리 
   - 데이터 클렌징 
   - 결측값 처리 (NaN / Null) 처리 
   - 데이터 인코딩 ( 레이블, 원 - 핫 - 인코딩 )
   - 데이터 스케일링 
   - 이상치 제거 
   - Feature 선택, 추출 가공 


데이터 인코딩 
    머신러닝 알고리즘은 문자열 데이터 속성을 입력 받지 않으며
    모든 데이터는 숫자형으로 표현되어야 함 
    문자열 카테고리형 속성은 모두 숫자값으로 변화 / 인코딩 되어야 함 

    - 레이블 ( Label ) 인코딩 
    - 원 핫 ( One - Hot) 인코딩 


 

```
#  EX) 

  상 품        가격     =>    상 품       가 격

   TV         1,000,000        0            ""

   냉장고     1,500,000        1            ""

   전자렌지     200.000        2            ""
   
   .                           3            ""
   .
   .
```



In [2]:
from sklearn.preprocessing import LabelEncoder

items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

#LabelEncoder를 객체로 생성한 후 , fit() 과 transform()으로 label 인코딩 수행 ,

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print("인코딩 변환값 :" ,labels)

인코딩 변환값 : [0 1 4 5 3 3 2 2]


In [6]:
print("인코딩 클래스:" , encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [7]:
print("디코딩 원본값:" , encoder.inverse_transform([4,5,2,0,1,1,3,3]))

디코딩 원본값: ['전자렌지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


=> 상품 이름 끼리 상하관계가 생기는 경우 발생 


# **원 핫 인코딩**

  원 핫 인코딩은 피처의 값의 유형에 따라 새로운 피처를 추가해 고유 값에 해당하는 컬럼에만 1을 표시 나머지에 0 표시

    사람 분류 _ TV    상품분류_냉장고    상품분류_믹서

    1                     0                   0
    0                     1                   0
    0                     0                   1

레이블 인코더 

Label Encoder 클래스 

fit() 과 transfor()을 이용해 변환 

원 핫 인코딩 



# **원 핫 인코딩 **

One-Hot-Encoding 클래스  

fit().과 transform()을 이용해 변환 
인자로 2차원 ndaray 입력 필요 
space 배열 형태로 변환되므로 
toarray()를 적용하여 다시 Dense 형태로 변환되어야 함 


pd.get_dummies(DataFrame)을 이용 

In [13]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np 

items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

# 2차원 ndarray로 변환
items = np.array(items).reshape(-1,1)

#원-핫 인코딩을 적용 
one_hot = OneHotEncoder()
one_hot.fit(items)
one_label = one_hot.transform(items)

# OneHotEncoder로 변환한 결과는 희소행렬(Sparse Matrix)이므로 toarray()를 이용하여 밀집 행렬(Dense Matrix)로 

print("원-핫 인코딩 데이터 ")
print(one_label.toarray())
print("원-핫 인코딩 데이터 차원")
print(one_label.shape)

원-핫 인코딩 데이터 
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [14]:
import pandas as pd 

df = pd.DataFrame({'item':['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서'] })
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자렌지  item_컴퓨터
0        1         0        0         0          0         0
1        0         1        0         0          0         0
2        0         0        0         0          1         0
3        0         0        0         0          0         1
4        0         0        0         1          0         0
5        0         0        0         1          0         0
6        0         0        1         0          0         0
7        0         0        1         0          0         0